name: Data LG ID Removal Check

on:
  pull_request:
    branches:
      - main
      - my-custom-branch-with-data-lg-id

jobs:
  check_data_lg_id_removal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check and notify
        id: set_flag
        run: |
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} | while read -r file; do
            echo "Checking file: $file"
            if git diff origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} -- "$file" | grep -q 'data-lg-id'; then
              echo "File $file has removed data-lg-id instances"
              has_removed_data_lg_id="true"  # Set the flag to true
              echo "::warning file=$file::Warning in $file"
            fi
          done
